### ISSUE TITLE
Random Expert: Crash on Keep floor symmetry puzzle

### ISSUE THREAD

**Issue by daschunk** [sigma144/witness-randomizer#12] opened 2020-04-07 15:24 UTC
Random Expert seed: 32621
Game crashes when stepping on the glass pane corresponding to the puzzle start. 
![20200407111004_1](https://user-images.githubusercontent.com/46092159/78687613-5a2b5800-78c2-11ea-859c-b432578ad685.jpg)

**Comment by sigma144** [comment] 2020-04-07 17:42
Hi daschunk, thanks for reporting this issue! Sadly, I can't seem to reproduce on my machine. However, I suspect it has something to do with removing symmetry from a symmetry puzzle. There is another puzzle where I do this and it sometimes crashes my game. I've never had this one crash on me though. I'll leave this issue open anyway, and hopefully once I fix the other crash issue will fix this one too.

**Comment by daschunk** [comment] 2020-04-08 03:51
Hi,

I found the other puzzle where the crash happens for the reason you described. I was able to progress past it by solving the vanilla puzzle and then running the randomizer afterwards.

**Comment by sigma144** [comment] 2020-04-10 17:10
I investigated the issue, and I believe I found a workaround for the one puzzle on symmetry island that crashes. Unfortunately, the same workaround does not work for the blue keep puzzle, as the pressure plate puzzles are extremely picky with what they will accept as a valid solution. I've never had any issues with the keep puzzle, so I'm hoping it was just a random glitch that won't happen again. One thing you could try is deleting your "puzzledata" file before running the randomizer.

Since I haven't been able to reproduce the error, I'm going to close the issue for now. Maybe if other people report the same issue, I can figure out what's going on. Thanks for your help!

**Closed by sigma144** 2020-04-10 17:10 UTC
